adjust_smallvolumes – SWMMengine
adjust_smallvolumes Subroutine
12 statements
Source File
public subroutine adjust_smallvolumes(elem2R, elem2I, elem2YN, e2r_VolumeColumn, elemMR, elemMI, elemMYN, eMr_VolumeColumn)
Arguments
Type Intent Optional Attributes Name
real, intent(inout) :: elem2R(:,:)
integer, intent(in) :: elem2I(:,:)
logical, intent(inout) :: elem2YN(:,:)
integer, intent(in) :: e2r_VolumeColumn
real, intent(inout) :: elemMR(:,:)
integer, intent(in) :: elemMI(:,:)
logical, intent(inout) :: elemMYN(:,:)
integer, intent(in) :: eMr_VolumeColumn
Calls
Called by
Contents
None
Call graph
adjust_smallvolumes calls smallvolume_geometry, smallvolume_identification
smallvolume_geometry calls smallvolume_junctionbranch_reset, smallvolume_element_geometry_reset
smallvolume_identification calls smallvolume_identification_for_element
element_geometry_update calls adjust_smallvolumes
rk2_update_auxiliary_variables calls element_geometry_update
initial_condition_setup calls element_geometry_update
main calls initial_condition_setup, time_marching
rk2 calls rk2_update_auxiliary_variables
time_marching calls rk2