diagnostic_volume_conservation – SWMMengine
diagnostic_volume_conservation Subroutine
42 statements
Source File
public subroutine diagnostic_volume_conservation(diagnostic, elem2R, elem2I, elemMR, elemMI, faceR, bcdataUp, bcdataDn, thisStep, diagnosticTask)
Arguments
Type Intent Optional Attributes Name
type(diagnosticType), intent(inout) :: diagnostic(:)
real, intent(inout) :: elem2R(:,:)
integer, intent(in), target :: elem2I(:,:)
real, intent(inout) :: elemMR(:,:)
integer, intent(in), target :: elemMI(:,:)
real, intent(inout) :: faceR(:,:)
type(bcType), intent(in) :: bcdataUp(:)
type(bcType), intent(in) :: bcdataDn(:)
integer, intent(in) :: thisStep
integer, intent(in) :: diagnosticTask
Calls
Called by
Contents
None
Call graph
diagnostic_volume_conservation calls total_inout_flowrate
total_inout_flowrate calls inout_flowrate_from_bcdata
diagnostic_initialize calls diagnostic_volume_conservation
time_marching calls diagnostic_volume_conservation
main calls diagnostic_initialize, time_marching