element_geometry_branch_fix – SWMMengine
element_geometry_branch_fix Subroutine
23 statements
Source File
public subroutine element_geometry_branch_fix(elemMR, elemMI, faceR, faceI)
Arguments
Type Intent Optional Attributes Name
real, intent(inout), target :: elemMR(:,:)
integer, intent(in) :: elemMI(:,:)
real, intent(in) :: faceR(:,:)
integer, intent(in) :: faceI(:,:)
Calls
Called by
Contents
None
Call graph
element_geometry_branch_fix calls rectangular_junction_leg, utility_advance_temp_array, junction_branch_velocity_and_flowrate_proportional_to_area, junction_branch_sum_areas_by_direction, adjust_junction_branch_velocity_limit, emr_temp
adjust_junction_branch_velocity_limit calls emr_flowratedn, emr_flowrateup, emr_velocityup, emr_velocitydn, emr_areadn, emr_areaup
rk2_update_auxiliary_variables calls element_geometry_branch_fix
rk2 calls rk2_update_auxiliary_variables
time_marching calls rk2
main calls time_marching