face_interp_for_elem2 – SWMMengine
face_interp_for_elem2 Subroutine
59 statements
Source File
private subroutine face_interp_for_elem2(elem2R, faceR, faceI, faceYN, bcdataDn, bcdataUp, e2r_Volume_new)
Arguments
Type Intent Optional Attributes Name
real, intent(in), target :: elem2R(:,:)
real, intent(inout), target :: faceR(:,:)
integer, intent(in) :: faceI(:,:)
logical, intent(inout), target :: faceYN(:,:)
type(bcType), intent(in) :: bcdataDn(:)
type(bcType), intent(in) :: bcdataUp(:)
integer, intent(in) :: e2r_Volume_new
Calls
Called by
Contents
None
Call graph
face_interp_for_elem2 calls utility_advance_temp_array, fyn_temp, fr_temp
face_update calls face_interp_for_elem2
rk2_update_auxiliary_variables calls face_update
initial_condition_setup calls face_update
main calls initial_condition_setup, time_marching
rk2 calls rk2_update_auxiliary_variables
time_marching calls rk2