face_update – SWMMengine
face_update Subroutine
32 statements
Source File
public subroutine face_update(elem2R, elem2I, elemMR, faceR, faceI, faceYN, bcdataDn, bcdataUp, e2r_Velocity_new, eMr_Velocity_new, e2r_Volume_new, eMr_Volume_new, thisTime, thisIter)
Arguments
Type Intent Optional Attributes Name
real, intent(inout) :: elem2R(:,:)
integer, intent(in) :: elem2I(:,:)
real, intent(in) :: elemMR(:,:)
real, intent(inout) :: faceR(:,:)
integer, intent(inout) :: faceI(:,:)
logical, intent(inout) :: faceYN(:,:)
type(bcType), intent(inout) :: bcdataDn(:)
type(bcType), intent(inout) :: bcdataUp(:)
integer, intent(in) :: e2r_Velocity_new
integer, intent(in) :: eMr_Velocity_new
integer, intent(in) :: e2r_Volume_new
integer, intent(in) :: eMr_Volume_new
real, intent(in) :: thisTime
integer, intent(in) :: thisIter
Calls
Called by
Contents
None
Call graph
face_update calls face_surface_elevation_interp, bc_applied_onface, face_hydraulic_jump, face_bc_flowrate_update, face_interp_for_elem2, face_interp_for_upstreamchannel_to_downstreamjunction, face_interp_for_downstreamchannel_to_upstreamjunction
face_surface_elevation_interp calls utility_advance_temp_array, emr_lengthdn, emr_lengthup, fyn_temp, fr_temp
bc_applied_onface calls bc_onface, bc_face_othervalues, bc_ghost_othervalues
face_hydraulic_jump calls utility_advance_temp_array, fr_temp
face_bc_flowrate_update calls face_bc_flowrate_update_onevalue
face_interp_for_elem2 calls utility_advance_temp_array, fyn_temp, fr_temp
face_interp_for_upstreamchannel_to_downstreamjunction calls utility_advance_temp_array, interp_with_junction_downstream, fyn_temp, emr_timescaleup, fr_temp
face_interp_for_downstreamchannel_to_upstreamjunction calls utility_advance_temp_array, interp_with_junction_upstream, emr_timescaledn, fyn_temp, fr_temp
interp_with_junction_upstream calls linear_interpolation
interp_with_junction_downstream calls linear_interpolation
bc_onface calls bc_updatevalue
bc_updatevalue calls utility_linear_interpolate_within_indexlist
rk2_update_auxiliary_variables calls face_update
initial_condition_setup calls face_update
main calls initial_condition_setup, time_marching
rk2 calls rk2_update_auxiliary_variables
time_marching calls rk2