initial_condition_setup – SWMMengine
initial_condition_setup Subroutine
27 statements
Source File
public subroutine initial_condition_setup(elem2R, elem2I, elem2YN, elemMR, elemMI, elemMYN, faceR, faceI, faceYN, linkR, linkI, nodeR, nodeI, bcdataDn, bcdataUp, thisTime)
Arguments
Type Intent Optional Attributes Name
real, intent(inout) :: elem2R(:,:)
integer, intent(inout) :: elem2I(:,:)
logical, intent(inout) :: elem2YN(:,:)
real, intent(inout) :: elemMR(:,:)
integer, intent(inout) :: elemMI(:,:)
logical, intent(inout) :: elemMYN(:,:)
real, intent(inout) :: faceR(:,:)
integer, intent(inout) :: faceI(:,:)
logical, intent(inout) :: faceYN(:,:)
real, intent(in) :: linkR(:,:)
integer, intent(in), target :: linkI(:,:)
real, intent(in) :: nodeR(:,:)
integer, intent(in), target :: nodeI(:,:)
type(bcType), intent(inout) :: bcdataDn(:)
type(bcType), intent(inout) :: bcdataUp(:)
real, intent(in) :: thisTime
Calls
Called by
Contents
None
Call graph
initial_condition_setup calls element_dynamics_update, bc_nullify_ghost_elem, face_update, element_geometry_update, initial_conditions_from_linkdata, initial_junction_conditions
element_dynamics_update calls bc_applied_onelement, adjust_zero_velocity_at_zero_volume, adjust_channel_velocity_limiter, element_flowrate_update, blended_smallvolume_velocity, element_timescale
face_update calls face_hydraulic_jump, face_interp_for_upstreamchannel_to_downstreamjunction, face_interp_for_downstreamchannel_to_upstreamjunction, face_surface_elevation_interp, bc_applied_onface, face_bc_flowrate_update, face_interp_for_elem2
element_geometry_update calls bc_applied_onelement, adjust_for_zero_geometry, rectangular_geometry_update, emr_temp, utility_advance_temp_array, adjust_smallvolumes
initial_junction_conditions calls junction_branch_velocities, junction_adjacent_element_average, junction_adjacent_element_values_to_branches, junction_branch_average_of_inflows_and_outflows
bc_applied_onelement calls bc_onelement
adjust_for_zero_geometry calls reset_juctionbranches_for_zero_values, reset_element_for_zero_values
face_hydraulic_jump calls utility_advance_temp_array, fr_temp
junction_branch_velocities calls junction_branch_velocities_one_direction
adjust_zero_velocity_at_zero_volume calls zero_velocity_at_zero_volume
junction_adjacent_element_average calls emr_temp, utility_advance_temp_array, junction_summation_from_adjacent_elements_one_direction
rectangular_geometry_update calls rectangular_junction_leg, rectangular_channel_or_junction
face_interp_for_upstreamchannel_to_downstreamjunction calls utility_advance_temp_array, interp_with_junction_downstream, fyn_temp, emr_timescaleup, fr_temp
face_interp_for_downstreamchannel_to_upstreamjunction calls utility_advance_temp_array, fyn_temp, fr_temp, emr_timescaledn, interp_with_junction_upstream
junction_adjacent_element_values_to_branches calls junction_adjacent_element_values_one_direction
element_flowrate_update calls emr_temp, utility_advance_temp_array, junction_branch_sum_areas_by_direction, adjust_junction_branch_velocity_limit, flowrate_from_velocity, junction_branch_velocity_and_flowrate_proportional_to_area
face_surface_elevation_interp calls utility_advance_temp_array, emr_lengthdn, emr_lengthup, fyn_temp, fr_temp
junction_branch_average_of_inflows_and_outflows calls emr_temp, utility_advance_temp_array, junction_net_inflow_and_outflow
bc_applied_onface calls bc_onface, bc_ghost_othervalues, bc_face_othervalues
face_bc_flowrate_update calls face_bc_flowrate_update_onevalue
face_interp_for_elem2 calls utility_advance_temp_array, fyn_temp, fr_temp
blended_smallvolume_velocity calls emi_mfaceup, emr_lengthdn, emr_velocitydn, emr_areadn, velocity_blend_with_mask, emr_lengthup, emr_flowratedn, emr_areaup, emi_mfacedn, emr_flowrateup, emr_velocityup
adjust_smallvolumes calls smallvolume_identification, smallvolume_geometry
element_timescale calls bc_timescale_value, timescale_value_junction, timescale_value_channel
bc_onface calls bc_updatevalue
smallvolume_identification calls smallvolume_identification_for_element
timescale_value_junction calls emr_temp, utility_advance_temp_array, timescale_limit_junction_one_direction, timescale_junction_one_direction
interp_with_junction_downstream calls linear_interpolation
velocity_blend_with_mask calls utility_advance_temp_array, velocity_blend, smallvolume_manningsn, small_chezy_velocity
adjust_junction_branch_velocity_limit calls emr_velocitydn, emr_areadn, emr_flowratedn, emr_areaup, emr_flowrateup, emr_velocityup
junction_net_inflow_and_outflow calls junction_net_flow_in_or_out
smallvolume_geometry calls smallvolume_junctionbranch_reset, smallvolume_element_geometry_reset
bc_onelement calls bc_updatevalue
timescale_value_channel calls utility_advance_temp_array, e2yn_temp, e2r_temp, timescale_limiter
interp_with_junction_upstream calls linear_interpolation
timescale_limit_junction_one_direction calls utility_advance_temp_array, timescale_limiter, emyn_temp
bc_updatevalue calls utility_linear_interpolate_within_indexlist
timescale_limiter calls apply_limiter_with_mask
main calls initial_condition_setup