initial_junction_conditions – SWMMengine
initial_junction_conditions Subroutine
30 statements
Source File
private subroutine initial_junction_conditions(faceR, faceI, elem2R, elem2I, elemMR, elemMI, nodeR, nodeI)
Arguments
Type Intent Optional Attributes Name
real, intent(in), target :: faceR(:,:)
integer, intent(in), target :: faceI(:,:)
real, intent(in), target :: elem2R(:,:)
integer, intent(in), target :: elem2I(:,:)
real, intent(inout) :: elemMR(:,:)
integer, intent(in), target :: elemMI(:,:)
real, intent(in), target :: nodeR(:,:)
integer, intent(in), target :: nodeI(:,:)
Calls
Called by
Contents
None
Call graph
initial_junction_conditions calls junction_adjacent_element_values_to_branches, junction_branch_average_of_inflows_and_outflows, junction_adjacent_element_average, junction_branch_velocities
junction_adjacent_element_values_to_branches calls junction_adjacent_element_values_one_direction
junction_branch_average_of_inflows_and_outflows calls junction_net_inflow_and_outflow, utility_advance_temp_array, emr_temp
junction_adjacent_element_average calls utility_advance_temp_array, emr_temp, junction_summation_from_adjacent_elements_one_direction
junction_branch_velocities calls junction_branch_velocities_one_direction
junction_net_inflow_and_outflow calls junction_net_flow_in_or_out
initial_condition_setup calls initial_junction_conditions
main calls initial_condition_setup