junction_geometry_setup – SWMMengine
junction_geometry_setup Subroutine
12 statements
Source File
public subroutine junction_geometry_setup(elemMR, elemMI)
Arguments
Type Intent Optional Attributes Name
real, intent(inout), target :: elemMR(:,:)
integer, intent(in) :: elemMI(:,:)
Calls
Called by
Contents
None
Call graph
junction_geometry_setup calls junction_branch_summation_and_updown_average, junction_branch_average_for_directions_then_sum
junction_branch_summation_and_updown_average calls utility_advance_temp_array, junction_branch_summation_one_direction, emr_temp
junction_branch_average_for_directions_then_sum calls utility_advance_temp_array, junction_branch_summation_one_direction, emr_temp
network_initiation calls junction_geometry_setup
main calls network_initiation