network_data_create – SWMMengine
network_data_create Subroutine
106 statements
Source File
private subroutine network_data_create(elem2R, elemMR, faceR, linkR, nodeR, elem2I, elemMI, faceI, linkI, nodeI, nodeYN, elem2Name, elemMName, faceName, linkName, nodeName)
Arguments
Type Intent Optional Attributes Name
real, intent(inout) :: elem2R(:,:)
real, intent(inout) :: elemMR(:,:)
real, intent(inout) :: faceR(:,:)
real, intent(in), target :: linkR(:,:)
real, intent(in), target :: nodeR(:,:)
integer, intent(inout) :: elem2I(:,:)
integer, intent(inout) :: elemMI(:,:)
integer, intent(inout) :: faceI(:,:)
integer, intent(inout) :: linkI(:,:)
integer, intent(inout), target :: nodeI(:,:)
logical, intent(in), target :: nodeYN(:,:)
type(string), intent(inout) :: elem2Name(:)
type(string), intent(inout) :: elemMName(:)
type(string), intent(inout) :: faceName(:)
type(string), intent(in) :: linkName(:)
type(string), intent(in) :: nodeName(:)
Calls
Called by
Contents
None
Call graph
network_data_create calls setassigned, handle_thisnode, subdivide_link_going_upstream
handle_thisnode calls setassigned, handle_thisnode, subdivide_link_going_upstream, emr_topwidthdn, emi_mfacedn, emr_topwidthup, emi_mfaceup, nr_elementlengthdn, emr_zbottomup, ni_mlinkup, emr_breadthscaledn, emr_breadthscaleup, setfacetype, emr_lengthdn, emr_zbottomdn, ni_mlinkdn, nr_elementlengthup, emr_lengthup
subdivide_link_going_upstream calls setfacetype
network_initiation calls network_data_create
main calls network_initiation