utility_scale_of_number – SWMMengine
utility_scale_of_number Function
4 statements
Source File
public pure elemental function utility_scale_of_number(inarray) result(outarray)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: inarray
Return Value integer
Called by
Contents
None
Call graph
this_setting_for_time_and_steps calls utility_scale_of_number, utility_round_to_significant_digits
utility_round_to_significant_digits calls utility_scale_of_number
test_case_initiation calls this_setting_for_time_and_steps
main calls test_case_initiation