main – SWMMengine
main Program
100 statements
Source File
Uses
allocate_storage
array_index
bc
checking
data_keys
debug
diagnostic
globals
initialization
initial_condition
junction
network_define
output
setting_definition
type_definitions
test_cases
time_loop
utility
Calls
Contents
Variables
elem2R elem2I elem2YN elem2Name elemMR elemMI elemMYN elemMName faceR faceI faceYN faceName linkR linkI linkYN linkName nodeR nodeI nodeYN nodeName bcdataUp bcdataDn debugfile diagnostic threadedfile
Variables
Type Attributes Name Initial
real, dimension(:,:), allocatable, target :: elem2R
integer, dimension(:,:), allocatable, target :: elem2I
logical, dimension(:,:), allocatable, target :: elem2YN
type(string), dimension(:), allocatable, target :: elem2Name
real, dimension(:,:), allocatable, target :: elemMR
integer, dimension(:,:), allocatable, target :: elemMI
logical, dimension(:,:), allocatable, target :: elemMYN
type(string), dimension(:), allocatable, target :: elemMName
real, dimension(:,:), allocatable, target :: faceR
integer, dimension(:,:), allocatable, target :: faceI
logical, dimension(:,:), allocatable, target :: faceYN
type(string), dimension(:), allocatable, target :: faceName
real, dimension(:,:), allocatable, target :: linkR
integer, dimension(:,:), allocatable, target :: linkI
logical, dimension(:,:), allocatable, target :: linkYN
type(string), dimension(:), allocatable, target :: linkName
real, dimension(:,:), allocatable, target :: nodeR
integer, dimension(:,:), allocatable, target :: nodeI
logical, dimension(:,:), allocatable, target :: nodeYN
type(string), dimension(:), allocatable, target :: nodeName
type(bcType), dimension(:), allocatable :: bcdataUp
type(bcType), dimension(:), allocatable :: bcdataDn
type(debugfileType), dimension(:), allocatable :: debugfile
type(diagnosticType), allocatable, dimension(:) :: diagnostic
type(threadedfileType), allocatable, dimension(:) :: threadedfile
Call graph
main calls initialize_arrayindex, test_case_initiation, checking_consistency, checking_smallvolume_consistency, emr_flowratedn, emr_flowrateup, utility_get_datetime_stamp, emr_velocityup, initialize_arrayindex_status, debug_initialize, diagnostic_initialize, emr_velocitydn, output_threaded_by_link_initialize, debug_finalize, initial_condition_setup, time_marching, network_initiation, setting_default, bc_checks
initialize_arrayindex calls emr_flowratedn, emr_flowrateup, emr_velocityup, emr_velocitydn, emr_timescaleall, emi_temp, emi_mfaceup, emr_breadthscaleup, emr_lengthdn, emr_zbottomall, emr_areadn, emr_etaup, emr_etaall, nr_elementlengthdn, fi_temp, emr_etadn, emr_lengthup, fyn_temp, emr_timescaleup, emr_breadthscaleall, emr_temp, fr_temp, emr_flowrateall, emr_topwidthup, emr_topwidthall, e2i_temp, emr_timescaledn, emr_velocityall, ni_mlinkdn, emr_areaup, nr_elementlengthup, emr_zbottomdn, emr_topwidthdn, emi_mfacedn, emi_mfaceall, e2yn_temp, e2r_temp, emr_zbottomup, ni_mlinkup, emr_breadthscaledn, emr_areaall, emr_lengthall, emr_hyddepthup, emyn_temp, emr_hyddepthdn, emr_hyddepthall
test_case_initiation calls this_setting_for_time_and_steps, control_variable_allocation, write_testcase_setup_file, case_y_channel_initialize
initialize_arrayindex_status calls emr_flowratedn, emr_flowrateup, emr_velocityup, emr_velocitydn, emi_mfaceup, emr_breadthscaleup, emr_lengthdn, emr_areadn, emr_etaup, nr_elementlengthdn, emr_etadn, emr_lengthup, emr_timescaleup, emr_temp, emr_topwidthup, emr_timescaledn, ni_mlinkdn, emr_areaup, nr_elementlengthup, emr_zbottomdn, emr_topwidthdn, emi_mfacedn, e2r_temp, emr_zbottomup, ni_mlinkup, emr_breadthscaledn, emr_hyddepthup, emr_hyddepthdn
debug_initialize calls utility_check_allocation
diagnostic_initialize calls utility_check_allocation, diagnostic_volume_conservation
output_threaded_by_link_initialize calls utility_check_allocation
initial_condition_setup calls bc_nullify_ghost_elem, initial_conditions_from_linkdata, element_dynamics_update, initial_junction_conditions, face_update, element_geometry_update
time_marching calls bc_applied_onelement, output_all_threaded_data_by_link, diagnostic_froude_number, diagnostic_cfl, debug_output, diagnostic_volume_conservation, rk2, bc_applied_onface
network_initiation calls network_data_create, network_check_bc, network_adjust_link_length, network_check_node_link_match, initialize_array_zerovalues, network_get_link_slope, network_count_elements_and_faces, network_node_assignment, junction_geometry_setup, allocate_data_storage, initialize_dummy_values, junction_branch_assigned_to_faces
bc_checks calls bc_adequate_coverage, bc_node_assignment_error_check, bc_updatevalue, bc_assign_faceid
bc_applied_onelement calls bc_onelement
network_data_create calls handle_thisnode, setassigned, subdivide_link_going_upstream
this_setting_for_time_and_steps calls utility_scale_of_number, get_dt_from_cfl, utility_round_to_significant_digits
network_adjust_link_length calls link_shortening
output_all_threaded_data_by_link calls output_one_threaded_data_by_link
network_check_node_link_match calls ni_mlinkdn, ni_mlinkup
diagnostic_froude_number calls diagnostic_froude_number_one
bc_adequate_coverage calls bc_adequate_coverage_onedir
write_testcase_setup_file calls utility_check_fileopen
initialize_array_zerovalues calls emr_lengthdn, emr_areadn, emr_lengthup, emr_topwidthup, emr_areaup, emr_topwidthdn, emr_hyddepthup, emr_hyddepthdn
diagnostic_volume_conservation calls total_inout_flowrate
element_dynamics_update calls bc_applied_onelement, adjust_zero_velocity_at_zero_volume, adjust_channel_velocity_limiter, element_flowrate_update, blended_smallvolume_velocity, element_timescale
junction_geometry_setup calls junction_branch_summation_and_updown_average, junction_branch_average_for_directions_then_sum
rk2 calls emr_temp, e2r_temp, rk2_update_auxiliary_variables, diagnostic_element_volume_conservation_fluxes, diagnostic_element_volume_conservation, utility_advance_temp_array, overwrite_old_values
initial_junction_conditions calls junction_branch_velocities, junction_adjacent_element_average, junction_adjacent_element_values_to_branches, junction_branch_average_of_inflows_and_outflows
case_y_channel_initialize calls bc_allocate, case_y_channel_links_and_nodes
allocate_data_storage calls utility_check_allocation
face_update calls bc_applied_onface, face_hydraulic_jump, face_interp_for_upstreamchannel_to_downstreamjunction, face_interp_for_downstreamchannel_to_upstreamjunction, face_surface_elevation_interp, face_bc_flowrate_update, face_interp_for_elem2
element_geometry_update calls bc_applied_onelement, emr_temp, adjust_for_zero_geometry, rectangular_geometry_update, utility_advance_temp_array, adjust_smallvolumes
bc_applied_onface calls bc_onface, bc_ghost_othervalues, bc_face_othervalues
bc_updatevalue calls utility_linear_interpolate_within_indexlist
initialize_dummy_values calls emi_mfaceup, emi_mfacedn
junction_branch_assigned_to_faces calls emi_mfaceup, emi_mfacedn
adjust_for_zero_geometry calls reset_juctionbranches_for_zero_values, reset_element_for_zero_values
handle_thisnode calls emi_mfaceup, emr_breadthscaleup, emr_lengthdn, nr_elementlengthdn, emr_lengthup, emr_topwidthup, ni_mlinkdn, nr_elementlengthup, emr_zbottomdn, emr_topwidthdn, emi_mfacedn, emr_zbottomup, ni_mlinkup, emr_breadthscaledn, handle_thisnode, setassigned, subdivide_link_going_upstream, setfacetype
face_hydraulic_jump calls fr_temp, utility_advance_temp_array
bc_onface calls bc_updatevalue
output_one_threaded_data_by_link calls emr_lengthdn, utility_check_allocation, emr_lengthup
junction_branch_summation_and_updown_average calls emr_temp, utility_advance_temp_array, junction_branch_summation_one_direction
rk2_update_auxiliary_variables calls element_dynamics_update, face_update, element_geometry_update, adjust_vshaped_flowrate, element_geometry_branch_fix
bc_allocate calls utility_check_allocation
junction_branch_velocities calls junction_branch_velocities_one_direction
adjust_zero_velocity_at_zero_volume calls zero_velocity_at_zero_volume
junction_adjacent_element_average calls emr_temp, utility_advance_temp_array, junction_summation_from_adjacent_elements_one_direction
diagnostic_element_volume_conservation_fluxes calls emi_mfaceup, emi_mfacedn
rectangular_geometry_update calls rectangular_junction_leg, rectangular_channel_or_junction
total_inout_flowrate calls inout_flowrate_from_bcdata
case_y_channel_links_and_nodes calls allocate_linknode_storage
face_interp_for_upstreamchannel_to_downstreamjunction calls fyn_temp, emr_timescaleup, fr_temp, utility_advance_temp_array, interp_with_junction_downstream
face_interp_for_downstreamchannel_to_upstreamjunction calls fyn_temp, fr_temp, emr_timescaledn, utility_advance_temp_array, interp_with_junction_upstream
junction_branch_average_for_directions_then_sum calls emr_temp, utility_advance_temp_array, junction_branch_summation_one_direction
junction_adjacent_element_values_to_branches calls junction_adjacent_element_values_one_direction
element_flowrate_update calls emr_temp, utility_advance_temp_array, junction_branch_sum_areas_by_direction, adjust_junction_branch_velocity_limit, flowrate_from_velocity, junction_branch_velocity_and_flowrate_proportional_to_area
bc_onelement calls bc_updatevalue
face_surface_elevation_interp calls emr_lengthdn, emr_lengthup, fyn_temp, fr_temp, utility_advance_temp_array
subdivide_link_going_upstream calls setfacetype
junction_branch_average_of_inflows_and_outflows calls emr_temp, utility_advance_temp_array, junction_net_inflow_and_outflow
face_bc_flowrate_update calls face_bc_flowrate_update_onevalue
face_interp_for_elem2 calls fyn_temp, fr_temp, utility_advance_temp_array
utility_round_to_significant_digits calls utility_scale_of_number
blended_smallvolume_velocity calls emr_flowratedn, emr_flowrateup, emr_velocityup, emr_velocitydn, emi_mfaceup, emr_lengthdn, emr_areadn, emr_lengthup, emr_areaup, emi_mfacedn, velocity_blend_with_mask
adjust_smallvolumes calls smallvolume_identification, smallvolume_geometry
element_timescale calls bc_timescale_value, timescale_value_junction, timescale_value_channel
smallvolume_identification calls smallvolume_identification_for_element
timescale_value_junction calls emr_temp, utility_advance_temp_array, timescale_limit_junction_one_direction, timescale_junction_one_direction
interp_with_junction_downstream calls linear_interpolation
velocity_blend_with_mask calls utility_advance_temp_array, velocity_blend, smallvolume_manningsn, small_chezy_velocity
adjust_junction_branch_velocity_limit calls emr_flowratedn, emr_flowrateup, emr_velocityup, emr_velocitydn, emr_areadn, emr_areaup
junction_net_inflow_and_outflow calls junction_net_flow_in_or_out
smallvolume_geometry calls smallvolume_junctionbranch_reset, smallvolume_element_geometry_reset
allocate_linknode_storage calls utility_check_allocation
adjust_vshaped_flowrate calls e2yn_temp, e2r_temp, utility_advance_temp_array, utility_sign_with_ones
timescale_value_channel calls e2yn_temp, e2r_temp, utility_advance_temp_array, timescale_limiter
element_geometry_branch_fix calls emr_temp, utility_advance_temp_array, rectangular_junction_leg, junction_branch_sum_areas_by_direction, adjust_junction_branch_velocity_limit, junction_branch_velocity_and_flowrate_proportional_to_area
interp_with_junction_upstream calls linear_interpolation
timescale_limit_junction_one_direction calls emyn_temp, utility_advance_temp_array, timescale_limiter
timescale_limiter calls apply_limiter_with_mask