allocate_data_storage – SWMMengine
allocate_data_storage Subroutine
48 statements
Source File
public subroutine allocate_data_storage(elem2R, elemMR, faceR, elem2I, elemMI, faceI, elem2YN, elemMYN, faceYN, elem2Name, elemMName, faceName)
Arguments
Type Intent Optional Attributes Name
real, intent(out), dimension(:,:), allocatable, target :: elem2R
real, intent(out), dimension(:,:), allocatable, target :: elemMR
real, intent(out), dimension(:,:), allocatable, target :: faceR
integer, intent(out), dimension(:,:), allocatable, target :: elem2I
integer, intent(out), dimension(:,:), allocatable, target :: elemMI
integer, intent(out), dimension(:,:), allocatable, target :: faceI
logical, intent(out), dimension(:,:), allocatable, target :: elem2YN
logical, intent(out), dimension(:,:), allocatable, target :: elemMYN
logical, intent(out), dimension(:,:), allocatable, target :: faceYN
type(string), intent(out), dimension(:), allocatable, target :: elem2Name
type(string), intent(out), dimension(:), allocatable, target :: elemMName
type(string), intent(out), dimension(:), allocatable, target :: faceName
Calls
Called by
Contents
None
Call graph
allocate_data_storage calls utility_check_allocation
network_initiation calls allocate_data_storage
main calls network_initiation