allocate_linknode_storage – SWMMengine
allocate_linknode_storage Subroutine
35 statements
Source File
public subroutine allocate_linknode_storage(linkR, nodeR, linkI, nodeI, linkYN, nodeYN, linkName, nodeName)
Arguments
Type Intent Optional Attributes Name
real, intent(out), dimension(:,:), allocatable, target :: linkR
real, intent(out), dimension(:,:), allocatable, target :: nodeR
integer, intent(out), dimension(:,:), allocatable, target :: linkI
integer, intent(out), dimension(:,:), allocatable, target :: nodeI
logical, intent(out), dimension(:,:), allocatable, target :: linkYN
logical, intent(out), dimension(:,:), allocatable, target :: nodeYN
type(string), intent(out), dimension(:), allocatable, target :: linkName
type(string), intent(out), dimension(:), allocatable, target :: nodeName
Calls
Called by
Contents
None
Call graph
allocate_linknode_storage calls utility_check_allocation
case_y_channel_links_and_nodes calls allocate_linknode_storage
case_simple_channel_links_and_nodes calls allocate_linknode_storage
case_simple_channel_initialize calls case_simple_channel_links_and_nodes
case_y_channel_initialize calls case_y_channel_links_and_nodes
test_case_initiation calls case_y_channel_initialize
main calls test_case_initiation