bc_checks – SWMMengine
bc_checks Subroutine
15 statements
Source File
public subroutine bc_checks(bcdataUp, bcdataDn, elem2I, faceI, nodeI)
Arguments
Type Intent Optional Attributes Name
type(bcType), intent(inout) :: bcdataUp(:)
type(bcType), intent(inout) :: bcdataDn(:)
integer, intent(in) :: elem2I(:,:)
integer, intent(in) :: faceI(:,:)
integer, intent(in), target :: nodeI(:,:)
Calls
Called by
Contents
None
Call graph
bc_checks calls bc_updatevalue, bc_adequate_coverage, bc_node_assignment_error_check, bc_assign_faceid
bc_updatevalue calls utility_linear_interpolate_within_indexlist
bc_adequate_coverage calls bc_adequate_coverage_onedir
main calls bc_checks