bc_face_othervalues – SWMMengine
bc_face_othervalues Subroutine
66 statements
Source File
private subroutine bc_face_othervalues(faceR, faceI, elem2R, bcdata)
Arguments
Type Intent Optional Attributes Name
real, intent(inout), target :: faceR(:,:)
integer, intent(in), target :: faceI(:,:)
real, intent(in), target :: elem2R(:,:)
type(bcType), intent(in), target :: bcdata(:)
Called by
Contents
None
Call graph
bc_applied_onface calls bc_face_othervalues
face_update calls bc_applied_onface
time_marching calls bc_applied_onface, rk2
explicit_test_advance calls bc_applied_onface
explicit_euler_advance calls bc_applied_onface
main calls time_marching, initial_condition_setup
rk2_update_auxiliary_variables calls face_update
initial_condition_setup calls face_update
rk2 calls rk2_update_auxiliary_variables