bc_onelement – SWMMengine
bc_onelement Subroutine
30 statements
Source File
private subroutine bc_onelement(elem2R, bcdata, thisTime, thiscategory, e2r_VelocityColumn)
Arguments
Type Intent Optional Attributes Name
real, intent(inout) :: elem2R(:,:)
type(bcType), intent(inout), target :: bcdata(:)
real, intent(in) :: thisTime
integer, intent(in) :: thiscategory
integer, intent(in) :: e2r_VelocityColumn
Calls
Called by
Contents
None
Call graph
bc_onelement calls bc_updatevalue
bc_updatevalue calls utility_linear_interpolate_within_indexlist
bc_applied_onelement calls bc_onelement
element_geometry_update calls bc_applied_onelement
time_marching calls bc_applied_onelement, rk2
element_dynamics_update calls bc_applied_onelement
explicit_test_advance calls bc_applied_onelement
explicit_euler_advance calls bc_applied_onelement
main calls time_marching, initial_condition_setup
rk2_update_auxiliary_variables calls element_geometry_update, element_dynamics_update
initial_condition_setup calls element_geometry_update, element_dynamics_update
rk2 calls rk2_update_auxiliary_variables