bc_updatevalue – SWMMengine
bc_updatevalue Subroutine
12 statements
Source File
private subroutine bc_updatevalue(bcdata, thisTime)
Arguments
Type Intent Optional Attributes Name
type(bcType), intent(inout) :: bcdata(:)
real, intent(in) :: thisTime
Calls
Called by
Contents
None
Call graph
bc_updatevalue calls utility_linear_interpolate_within_indexlist
bc_onface calls bc_updatevalue
bc_onelement calls bc_updatevalue
bc_checks calls bc_updatevalue
bc_applied_onelement calls bc_onelement
main calls bc_checks, time_marching, initial_condition_setup
bc_applied_onface calls bc_onface
element_geometry_update calls bc_applied_onelement
face_update calls bc_applied_onface
explicit_euler_advance calls bc_applied_onelement, bc_applied_onface
time_marching calls bc_applied_onelement, bc_applied_onface, rk2
element_dynamics_update calls bc_applied_onelement
explicit_test_advance calls bc_applied_onelement, bc_applied_onface
rk2_update_auxiliary_variables calls element_geometry_update, face_update, element_dynamics_update
initial_condition_setup calls element_geometry_update, face_update, element_dynamics_update
rk2 calls rk2_update_auxiliary_variables