blended_smallvolume_velocity – SWMMengine
blended_smallvolume_velocity Subroutine
21 statements
Source File
private subroutine blended_smallvolume_velocity(elem2R, elem2I, elem2YN, elemMR, elemMI, elemMYN, faceR, e2r_Velocity_new, eMr_Velocity_new)
Arguments
Type Intent Optional Attributes Name
real, intent(inout), target :: elem2R(:,:)
integer, intent(in), target :: elem2I(:,:)
logical, intent(in) :: elem2YN(:,:)
real, intent(inout), target :: elemMR(:,:)
integer, intent(in), target :: elemMI(:,:)
logical, intent(in) :: elemMYN(:,:)
real, intent(in), target :: faceR(:,:)
integer, intent(in) :: e2r_Velocity_new
integer, intent(in) :: eMr_Velocity_new
Calls
Called by
Contents
None
Call graph
blended_smallvolume_velocity calls emi_mfacedn, emr_flowratedn, emi_mfaceup, emr_flowrateup, emr_velocityup, emr_lengthdn, velocity_blend_with_mask, emr_velocitydn, emr_areadn, emr_areaup, emr_lengthup
velocity_blend_with_mask calls utility_advance_temp_array, smallvolume_manningsn, small_chezy_velocity, velocity_blend
element_dynamics_update calls blended_smallvolume_velocity
rk2_update_auxiliary_variables calls element_dynamics_update
initial_condition_setup calls element_dynamics_update
main calls initial_condition_setup, time_marching
rk2 calls rk2_update_auxiliary_variables
time_marching calls rk2