case_y_channel_initialize – SWMMengine
case_y_channel_initialize Subroutine
40 statements
Source File
public subroutine case_y_channel_initialize(channel_length, channel_breadth, subdivide_length, lowerZ, upperZ, initial_flowrate, depth_upstream, depth_dnstream, ManningsN, roughness_type, idepth_type, linkR, nodeR, linkI, nodeI, linkYN, nodeYN, linkName, nodeName, bcdataDn, bcdataUp)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: channel_length(:)
real, intent(in) :: channel_breadth(:)
real, intent(in) :: subdivide_length(:)
real, intent(in) :: lowerZ(:)
real, intent(in) :: upperZ(:)
real, intent(in) :: initial_flowrate(:)
real, intent(in) :: depth_upstream(:)
real, intent(in) :: depth_dnstream(:)
real, intent(in) :: ManningsN(:)
integer, intent(in) :: roughness_type
integer, intent(in) :: idepth_type(:)
real, intent(out), dimension(:,:), allocatable, target :: linkR
real, intent(out), dimension(:,:), allocatable, target :: nodeR
integer, intent(out), dimension(:,:), allocatable, target :: linkI
integer, intent(out), dimension(:,:), allocatable, target :: nodeI
logical, intent(out), dimension(:,:), allocatable, target :: linkYN
logical, intent(out), dimension(:,:), allocatable, target :: nodeYN
type(string), intent(out), dimension(:), allocatable, target :: linkName
type(string), intent(out), dimension(:), allocatable, target :: nodeName
type(bcType), intent(out), dimension(:), allocatable :: bcdataDn
type(bcType), intent(out), dimension(:), allocatable :: bcdataUp
Calls
Called by
Contents
None
Call graph
case_y_channel_initialize calls case_y_channel_links_and_nodes, bc_allocate
case_y_channel_links_and_nodes calls allocate_linknode_storage
bc_allocate calls utility_check_allocation
allocate_linknode_storage calls utility_check_allocation
test_case_initiation calls case_y_channel_initialize
main calls test_case_initiation