element_dynamics_update – SWMMengine
element_dynamics_update Subroutine
26 statements
Source File
public subroutine element_dynamics_update(elem2R, elemMR, faceR, elem2I, elemMI, elem2YN, elemMYN, bcdataDn, bcdataUp, e2r_Velocity_new, eMr_Velocity_new, e2r_Volume_new, eMr_Volume_new, thisTime)
Arguments
Type Intent Optional Attributes Name
real, intent(inout), target :: elem2R(:,:)
real, intent(inout), target :: elemMR(:,:)
real, intent(in), target :: faceR(:,:)
integer, intent(in) :: elem2I(:,:)
integer, intent(in) :: elemMI(:,:)
logical, intent(inout), target :: elem2YN(:,:)
logical, intent(inout), target :: elemMYN(:,:)
type(bcType), intent(inout) :: bcdataDn(:)
type(bcType), intent(inout) :: bcdataUp(:)
integer, intent(in) :: e2r_Velocity_new
integer, intent(in) :: eMr_Velocity_new
integer, intent(in) :: e2r_Volume_new
integer, intent(in) :: eMr_Volume_new
real, intent(in) :: thisTime
Calls
Called by
Contents
None
Call graph
element_dynamics_update calls adjust_channel_velocity_limiter, blended_smallvolume_velocity, element_flowrate_update, bc_applied_onelement, adjust_zero_velocity_at_zero_volume, element_timescale
blended_smallvolume_velocity calls emi_mfaceup, emr_velocitydn, emr_flowrateup, emr_flowratedn, velocity_blend_with_mask, emi_mfacedn, emr_areaup, emr_lengthup, emr_velocityup, emr_lengthdn, emr_areadn
element_flowrate_update calls junction_branch_velocity_and_flowrate_proportional_to_area, emr_temp, flowrate_from_velocity, utility_advance_temp_array, junction_branch_sum_areas_by_direction, adjust_junction_branch_velocity_limit
bc_applied_onelement calls bc_onelement
adjust_zero_velocity_at_zero_volume calls zero_velocity_at_zero_volume
element_timescale calls timescale_value_junction, bc_timescale_value, timescale_value_channel
timescale_value_junction calls emr_temp, utility_advance_temp_array, timescale_limit_junction_one_direction, timescale_junction_one_direction
timescale_value_channel calls utility_advance_temp_array, timescale_limiter, e2r_temp, e2yn_temp
velocity_blend_with_mask calls utility_advance_temp_array, smallvolume_manningsn, velocity_blend, small_chezy_velocity
bc_onelement calls bc_updatevalue
adjust_junction_branch_velocity_limit calls emr_velocitydn, emr_flowrateup, emr_flowratedn, emr_areaup, emr_velocityup, emr_areadn
bc_updatevalue calls utility_linear_interpolate_within_indexlist
timescale_limiter calls apply_limiter_with_mask
timescale_limit_junction_one_direction calls utility_advance_temp_array, timescale_limiter, emyn_temp
rk2_update_auxiliary_variables calls element_dynamics_update
initial_condition_setup calls element_dynamics_update
main calls initial_condition_setup, time_marching
rk2 calls rk2_update_auxiliary_variables
time_marching calls rk2