element_geometry_update – SWMMengine
element_geometry_update Subroutine
35 statements
Source File
public subroutine element_geometry_update(elem2R, elem2I, elem2YN, e2r_VolumeColumn, elemMR, elemMI, elemMYN, eMr_VolumeColumn, faceR, faceI, bcdataDn, bcdataUp, thisTime, method_EtaM)
Arguments
Type Intent Optional Attributes Name
real, intent(inout), target :: elem2R(:,:)
integer, intent(inout), target :: elem2I(:,:)
logical, intent(inout), target :: elem2YN(:,:)
integer, intent(in) :: e2r_VolumeColumn
real, intent(inout), target :: elemMR(:,:)
integer, intent(inout), target :: elemMI(:,:)
logical, intent(inout), target :: elemMYN(:,:)
integer, intent(in) :: eMr_VolumeColumn
real, intent(in) :: faceR(:,:)
integer, intent(in) :: faceI(:,:)
type(bcType), intent(inout) :: bcdataDn(:)
type(bcType), intent(inout) :: bcdataUp(:)
real, intent(in) :: thisTime
integer, intent(in) :: method_EtaM
Calls
Called by
Contents
None
Call graph
element_geometry_update calls bc_applied_onelement, adjust_for_zero_geometry, utility_advance_temp_array, rectangular_geometry_update, adjust_smallvolumes, emr_temp
bc_applied_onelement calls bc_onelement
adjust_for_zero_geometry calls reset_juctionbranches_for_zero_values, reset_element_for_zero_values
rectangular_geometry_update calls rectangular_junction_leg, rectangular_channel_or_junction
adjust_smallvolumes calls smallvolume_geometry, smallvolume_identification
smallvolume_geometry calls smallvolume_junctionbranch_reset, smallvolume_element_geometry_reset
smallvolume_identification calls smallvolume_identification_for_element
bc_onelement calls bc_updatevalue
bc_updatevalue calls utility_linear_interpolate_within_indexlist
rk2_update_auxiliary_variables calls element_geometry_update
initial_condition_setup calls element_geometry_update
main calls initial_condition_setup, time_marching
rk2 calls rk2_update_auxiliary_variables
time_marching calls rk2