element_timescale – SWMMengine
element_timescale Subroutine
14 statements
Source File
private subroutine element_timescale(elem2R, elem2I, elem2YN, elemMR, elemMI, elemMYN, bcdataDn, bcdataUp, e2r_Velocity_new)
Arguments
Type Intent Optional Attributes Name
real, intent(inout) :: elem2R(:,:)
integer, intent(in) :: elem2I(:,:)
logical, intent(inout) :: elem2YN(:,:)
real, intent(inout) :: elemMR(:,:)
integer, intent(in) :: elemMI(:,:)
logical, intent(inout) :: elemMYN(:,:)
type(bcType), intent(in) :: bcdataDn(:)
type(bcType), intent(in) :: bcdataUp(:)
integer, intent(in) :: e2r_Velocity_new
Calls
Called by
Contents
None
Call graph
element_timescale calls timescale_value_channel, timescale_value_junction, bc_timescale_value
timescale_value_channel calls timescale_limiter, e2r_temp, e2yn_temp, utility_advance_temp_array
timescale_value_junction calls timescale_limit_junction_one_direction, timescale_junction_one_direction, utility_advance_temp_array, emr_temp
timescale_limiter calls apply_limiter_with_mask
timescale_limit_junction_one_direction calls timescale_limiter, utility_advance_temp_array, emyn_temp
element_dynamics_update calls element_timescale
rk2_update_auxiliary_variables calls element_dynamics_update
initial_condition_setup calls element_dynamics_update
main calls initial_condition_setup, time_marching
rk2 calls rk2_update_auxiliary_variables
time_marching calls rk2