element_flowrate_update – SWMMengine
element_flowrate_update Subroutine
26 statements
Source File
private subroutine element_flowrate_update(elem2R, elemMR, faceR, elem2I, elemMI, e2r_Velocity_new, eMr_Velocity_new)
Arguments
Type Intent Optional Attributes Name
real, intent(inout), target :: elem2R(:,:)
real, intent(inout), target :: elemMR(:,:)
real, intent(in), target :: faceR(:,:)
integer, intent(in), target :: elem2I(:,:)
integer, intent(in), target :: elemMI(:,:)
integer, intent(in) :: e2r_Velocity_new
integer, intent(in) :: eMr_Velocity_new
Calls
Called by
Contents
None
Call graph
element_flowrate_update calls flowrate_from_velocity, junction_branch_velocity_and_flowrate_proportional_to_area, adjust_junction_branch_velocity_limit, utility_advance_temp_array, junction_branch_sum_areas_by_direction, emr_temp
adjust_junction_branch_velocity_limit calls emr_areaup, emr_flowrateup, emr_velocityup, emr_areadn, emr_flowratedn, emr_velocitydn
element_dynamics_update calls element_flowrate_update
rk2_update_auxiliary_variables calls element_dynamics_update
initial_condition_setup calls element_dynamics_update
main calls initial_condition_setup, time_marching
rk2 calls rk2_update_auxiliary_variables
time_marching calls rk2