explicit_test_advance – SWMMengine
explicit_test_advance Subroutine
78 statements
Source File
public subroutine explicit_test_advance(elem2R, elem2I, elem2YN, elemMR, elemMI, elemMYN, faceR, faceI, faceYN, bcdataDn, bcdataUp, thistime, dt)
Arguments
Type Intent Optional Attributes Name
real, intent(inout), target :: elem2R(:,:)
integer, intent(inout), target :: elem2I(:,:)
logical, intent(inout), target :: elem2YN(:,:)
real, intent(inout), target :: elemMR(:,:)
integer, intent(inout), target :: elemMI(:,:)
logical, intent(inout), target :: elemMYN(:,:)
real, intent(inout), target :: faceR(:,:)
integer, intent(inout), target :: faceI(:,:)
logical, intent(inout), target :: faceYN(:,:)
type(bcType), intent(inout) :: bcdataDn(:)
type(bcType), intent(inout) :: bcdataUp(:)
real, intent(in) :: thistime
real, intent(in) :: dt
Calls
Contents
None
Call graph
explicit_test_advance calls fi_temp, e2r_temp, adjust_vshaped_flowrate, bc_applied_onelement, test_face_update, utility_advance_temp_array, bc_applied_onface
adjust_vshaped_flowrate calls e2r_temp, utility_advance_temp_array, e2yn_temp, utility_sign_with_ones
bc_applied_onelement calls bc_onelement
test_face_update calls e2r_temp, utility_advance_temp_array
bc_applied_onface calls bc_face_othervalues, bc_ghost_othervalues, bc_onface
bc_onelement calls bc_updatevalue
bc_onface calls bc_updatevalue
bc_updatevalue calls utility_linear_interpolate_within_indexlist