face_interp_for_upstreamchannel_to_downstreamjunction – SWMMengine
face_interp_for_upstreamchannel_to_downstreamjunction Subroutine
52 statements
Source File
private subroutine face_interp_for_upstreamchannel_to_downstreamjunction(elem2R, elemMR, faceR, faceI, faceYN, e2r_Volume_new, eMr_Volume_new)
Arguments
Type Intent Optional Attributes Name
real, intent(in), target :: elem2R(:,:)
real, intent(in), target :: elemMR(:,:)
real, intent(inout), target :: faceR(:,:)
integer, intent(in) :: faceI(:,:)
logical, intent(inout), target :: faceYN(:,:)
integer, intent(in) :: e2r_Volume_new
integer, intent(in) :: eMr_Volume_new
Calls
Called by
Contents
None
Call graph
face_interp_for_upstreamchannel_to_downstreamjunction calls emr_timescaleup, fyn_temp, fr_temp, utility_advance_temp_array, interp_with_junction_downstream
interp_with_junction_downstream calls linear_interpolation
face_update calls face_interp_for_upstreamchannel_to_downstreamjunction
rk2_update_auxiliary_variables calls face_update
initial_condition_setup calls face_update
main calls initial_condition_setup, time_marching
rk2 calls rk2_update_auxiliary_variables
time_marching calls rk2