face_interp_for_downstreamchannel_to_upstreamjunction – SWMMengine
face_interp_for_downstreamchannel_to_upstreamjunction Subroutine
52 statements
Source File
private subroutine face_interp_for_downstreamchannel_to_upstreamjunction(elem2R, elemMR, faceR, faceI, faceYN, e2r_Volume_new, eMr_Volume_new)
Arguments
Type Intent Optional Attributes Name
real, intent(in), target :: elem2R(:,:)
real, intent(in), target :: elemMR(:,:)
real, intent(inout), target :: faceR(:,:)
integer, intent(in) :: faceI(:,:)
logical, intent(inout), target :: faceYN(:,:)
integer, intent(in) :: e2r_Volume_new
integer, intent(in) :: eMr_Volume_new
Calls
Called by
Contents
None
Call graph
face_interp_for_downstreamchannel_to_upstreamjunction calls fyn_temp, emr_timescaledn, utility_advance_temp_array, fr_temp, interp_with_junction_upstream
interp_with_junction_upstream calls linear_interpolation
face_update calls face_interp_for_downstreamchannel_to_upstreamjunction
rk2_update_auxiliary_variables calls face_update
initial_condition_setup calls face_update
main calls initial_condition_setup, time_marching
rk2 calls rk2_update_auxiliary_variables
time_marching calls rk2