handle_thisnode – SWMMengine
handle_thisnode Subroutine
223 statements
Source File
private recursive subroutine handle_thisnode(lastElem2, thisElem2, lastElemM, thisElemM, lastFace, thisFace, thisNode, thisLink, elem2I, elemMI, faceI, linkI, nodeI, elem2R, elemMR, faceR, linkR, nodeR, elem2Name, elemMName, faceName, linkName, nodeName)
Arguments
Type Intent Optional Attributes Name
integer, intent(inout) :: lastElem2
integer, intent(inout) :: thisElem2
integer, intent(inout) :: lastElemM
integer, intent(inout) :: thisElemM
integer, intent(inout) :: lastFace
integer, intent(inout) :: thisFace
integer, intent(inout) :: thisNode
integer, intent(inout) :: thisLink
integer, intent(inout) :: elem2I(:,:)
integer, intent(inout) :: elemMI(:,:)
integer, intent(inout) :: faceI(:,:)
integer, intent(inout) :: linkI(:,:)
integer, intent(inout), target :: nodeI(:,:)
real, intent(inout) :: elem2R(:,:)
real, intent(inout) :: elemMR(:,:)
real, intent(inout) :: faceR(:,:)
real, intent(in), target :: linkR(:,:)
real, intent(in), target :: nodeR(:,:)
type(string), intent(inout) :: elem2Name(:)
type(string), intent(inout) :: elemMName(:)
type(string), intent(inout) :: faceName(:)
type(string), intent(in) :: linkName(:)
type(string), intent(in) :: nodeName(:)
Calls
Called by
Contents
None
Call graph
handle_thisnode calls handle_thisnode, emr_topwidthdn, emr_zbottomdn, emr_lengthup, setassigned, subdivide_link_going_upstream, ni_mlinkup, nr_elementlengthup, emr_zbottomup, emr_lengthdn, emi_mfaceup, emr_breadthscaledn, nr_elementlengthdn, emr_topwidthup, emr_breadthscaleup, ni_mlinkdn, emi_mfacedn, setfacetype
subdivide_link_going_upstream calls setfacetype
network_data_create calls handle_thisnode
network_initiation calls network_data_create
main calls network_initiation