initialize_array_zerovalues – SWMMengine
initialize_array_zerovalues Subroutine
20 statements
Source File
public subroutine initialize_array_zerovalues(elemMR)
Arguments
Type Intent Optional Attributes Name
real, intent(inout) :: elemMR(:,:)
Calls
Called by
Contents
None
Call graph
initialize_array_zerovalues calls emr_topwidthdn, emr_topwidthup, emr_lengthdn, emr_hyddepthup, emr_areadn, emr_areaup, emr_hyddepthdn, emr_lengthup
network_initiation calls initialize_array_zerovalues
main calls network_initiation