junction_branch_average_for_directions_then_sum – SWMMengine
junction_branch_average_for_directions_then_sum Subroutine
30 statements
Source File
private subroutine junction_branch_average_for_directions_then_sum(elemMR, elemMI, eMr_columnUp, eMr_columnDn, eMr_out)
Arguments
Type Intent Optional Attributes Name
real, intent(inout), target :: elemMR(:,:)
integer, intent(in) :: elemMI(:,:)
integer, intent(in) :: eMr_columnUp(:)
integer, intent(in) :: eMr_columnDn(:)
integer, intent(in) :: eMr_out
Calls
Called by
Contents
None
Call graph
junction_branch_average_for_directions_then_sum calls junction_branch_summation_one_direction, emr_temp, utility_advance_temp_array
junction_geometry_setup calls junction_branch_average_for_directions_then_sum
network_initiation calls junction_geometry_setup
main calls network_initiation