junction_net_inflow_and_outflow – SWMMengine
junction_net_inflow_and_outflow Subroutine
10 statements
Source File
private subroutine junction_net_inflow_and_outflow(eMr_inflow, eMr_outflow, elemMR, elemMI)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: eMr_inflow
integer, intent(in) :: eMr_outflow
real, intent(inout) :: elemMR(:,:)
integer, intent(in) :: elemMI(:,:)
Calls
Called by
Contents
None
Call graph
junction_net_inflow_and_outflow calls junction_net_flow_in_or_out
junction_branch_average_of_inflows_and_outflows calls junction_net_inflow_and_outflow
initial_junction_conditions calls junction_branch_average_of_inflows_and_outflows
initial_condition_setup calls initial_junction_conditions
main calls initial_condition_setup