junction_branch_velocities_one_direction – SWMMengine
junction_branch_velocities_one_direction Subroutine
15 statements
Source File
private subroutine junction_branch_velocities_one_direction(elemMR, elemMI, dir_face_per_elemM, eMi_nfaces_dir, eMr_FlowrateDir, eMr_AreaDir, eMr_VelocityDir)
Arguments
Type Intent Optional Attributes Name
real, intent(inout) :: elemMR(:,:)
integer, intent(in) :: elemMI(:,:)
integer, intent(in) :: dir_face_per_elemM
integer, intent(in) :: eMi_nfaces_dir
integer, intent(in) :: eMr_FlowrateDir(:)
integer, intent(in) :: eMr_AreaDir(:)
integer, intent(in) :: eMr_VelocityDir(:)
Called by
Contents
None
Call graph
junction_branch_velocities calls junction_branch_velocities_one_direction
initial_junction_conditions calls junction_branch_velocities
initial_condition_setup calls initial_junction_conditions
main calls initial_condition_setup