junction_branch_average_of_inflows_and_outflows – SWMMengine
junction_branch_average_of_inflows_and_outflows Subroutine
23 statements
Source File
public subroutine junction_branch_average_of_inflows_and_outflows(elemMR, elemMI)
Arguments
Type Intent Optional Attributes Name
real, intent(inout), target :: elemMR(:,:)
integer, intent(in) :: elemMI(:,:)
Calls
Called by
Contents
None
Call graph
junction_branch_average_of_inflows_and_outflows calls utility_advance_temp_array, junction_net_inflow_and_outflow, emr_temp
junction_net_inflow_and_outflow calls junction_net_flow_in_or_out
initial_junction_conditions calls junction_branch_average_of_inflows_and_outflows
initial_condition_setup calls initial_junction_conditions
main calls initial_condition_setup