junction_branch_summation_one_direction – SWMMengine
junction_branch_summation_one_direction Subroutine
15 statements
Source File
private subroutine junction_branch_summation_one_direction(eMr_sumvalue, elemMR, elemMI, face_per_elemM, eMi_nfaces_dir, eMr_columnDir)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: eMr_sumvalue
real, intent(inout) :: elemMR(:,:)
integer, intent(in) :: elemMI(:,:)
integer, intent(in) :: face_per_elemM
integer, intent(in) :: eMi_nfaces_dir
integer, intent(in) :: eMr_columnDir(:)
Called by
Contents
None
Call graph
junction_branch_summation_and_updown_average calls junction_branch_summation_one_direction
junction_branch_average_for_directions_then_sum calls junction_branch_summation_one_direction
junction_branch_summation calls junction_branch_summation_one_direction
junction_branch_average calls junction_branch_summation
junction_geometry_setup calls junction_branch_summation_and_updown_average, junction_branch_average_for_directions_then_sum
network_initiation calls junction_geometry_setup
main calls network_initiation