network_initiation – SWMMengine
network_initiation Subroutine
101 statements
Source File
public subroutine network_initiation(linkI, linkR, linkYN, linkName, nodeI, nodeR, nodeYN, nodeName, elem2R, elem2I, elem2YN, elem2Name, elemMR, elemMI, elemMYN, elemMName, faceR, faceI, faceYN, faceName)
Arguments
Type Intent Optional Attributes Name
integer, intent(inout), target :: linkI(:,:)
real, intent(inout) :: linkR(:,:)
logical, intent(inout) :: linkYN(:,:)
type(string), intent(inout) :: linkName(:)
integer, intent(inout), target :: nodeI(:,:)
real, intent(inout), target :: nodeR(:,:)
logical, intent(out) :: nodeYN(:,:)
type(string), intent(inout) :: nodeName(:)
real, dimension(:,:), allocatable, target :: elem2R
integer, dimension(:,:), allocatable, target :: elem2I
logical, dimension(:,:), allocatable, target :: elem2YN
type(string), dimension(:), allocatable, target :: elem2Name
real, dimension(:,:), allocatable, target :: elemMR
integer, dimension(:,:), allocatable, target :: elemMI
logical, dimension(:,:), allocatable, target :: elemMYN
type(string), dimension(:), allocatable, target :: elemMName
real, dimension(:,:), allocatable, target :: faceR
integer, dimension(:,:), allocatable, target :: faceI
logical, dimension(:,:), allocatable, target :: faceYN
type(string), dimension(:), allocatable, target :: faceName
Calls
Called by
Contents
None
Call graph
network_initiation calls network_get_link_slope, initialize_dummy_values, junction_branch_assigned_to_faces, network_node_assignment, initialize_array_zerovalues, network_data_create, allocate_data_storage, network_check_bc, network_check_node_link_match, junction_geometry_setup, network_count_elements_and_faces, network_adjust_link_length
initialize_dummy_values calls emi_mfaceup, emi_mfacedn
junction_branch_assigned_to_faces calls emi_mfaceup, emi_mfacedn
initialize_array_zerovalues calls emr_topwidthdn, emr_areaup, emr_lengthup, emr_areadn, emr_lengthdn, emr_hyddepthdn, emr_topwidthup, emr_hyddepthup
network_data_create calls handle_thisnode, subdivide_link_going_upstream, setassigned
allocate_data_storage calls utility_check_allocation
network_check_node_link_match calls ni_mlinkup, ni_mlinkdn
junction_geometry_setup calls junction_branch_summation_and_updown_average, junction_branch_average_for_directions_then_sum
network_adjust_link_length calls link_shortening
junction_branch_summation_and_updown_average calls junction_branch_summation_one_direction, emr_temp, utility_advance_temp_array
handle_thisnode calls emr_topwidthdn, handle_thisnode, emr_lengthup, subdivide_link_going_upstream, setassigned, ni_mlinkup, emr_lengthdn, emi_mfaceup, emr_topwidthup, ni_mlinkdn, emi_mfacedn, emr_zbottomdn, nr_elementlengthup, emr_zbottomup, emr_breadthscaledn, nr_elementlengthdn, emr_breadthscaleup, setfacetype
junction_branch_average_for_directions_then_sum calls junction_branch_summation_one_direction, emr_temp, utility_advance_temp_array
subdivide_link_going_upstream calls setfacetype
main calls network_initiation