rectangular_junction_leg – SWMMengine
rectangular_junction_leg Subroutine
55 statements
Source File
private subroutine rectangular_junction_leg(elemMR, elemMI, faceR, face_per_elemM, eMi_nfacesDir, eMi_MfaceDir, eMr_AreaDir, eMr_ZbottomDir, eMr_BreadthScaleDir, eMr_TopwidthDir, eMr_EtaDir, eMr_HydDepthDir, eMr_EtaOld, fr_Eta_dir, method_EtaM)
Arguments
Type Intent Optional Attributes Name
real, intent(inout), target :: elemMR(:,:)
integer, intent(in), target :: elemMI(:,:)
real, intent(in), target :: faceR(:,:)
integer, intent(in) :: face_per_elemM
integer, intent(in) :: eMi_nfacesDir
integer, intent(in) :: eMi_MfaceDir(:)
integer, intent(in) :: eMr_AreaDir(:)
integer, intent(in) :: eMr_ZbottomDir(:)
integer, intent(in) :: eMr_BreadthScaleDir(:)
integer, intent(in) :: eMr_TopwidthDir(:)
integer, intent(in) :: eMr_EtaDir(:)
integer, intent(in) :: eMr_HydDepthDir(:)
integer, intent(in) :: eMr_EtaOld
integer, intent(in) :: fr_Eta_dir
integer, intent(in) :: method_EtaM
Called by
Contents
None
Call graph
rectangular_geometry_update calls rectangular_junction_leg
element_geometry_branch_fix calls rectangular_junction_leg
element_geometry_update calls rectangular_geometry_update
rk2_update_auxiliary_variables calls element_geometry_branch_fix, element_geometry_update
rk2 calls rk2_update_auxiliary_variables
initial_condition_setup calls element_geometry_update
main calls initial_condition_setup, time_marching
time_marching calls rk2