rk2 – SWMMengine
rk2 Subroutine
48 statements
Source File
public subroutine rk2(elem2R, elemMR, elem2I, elemMI, faceR, faceI, elem2YN, elemMYN, faceYN, bcdataDn, bcdataUp, thistime, dt)
Arguments
Type Intent Optional Attributes Name
real, intent(inout), target :: elem2R(:,:)
real, intent(inout), target :: elemMR(:,:)
integer, intent(inout), target :: elem2I(:,:)
integer, intent(inout), target :: elemMI(:,:)
real, intent(inout), target :: faceR(:,:)
integer, intent(inout), target :: faceI(:,:)
logical, intent(inout), target :: elem2YN(:,:)
logical, intent(inout), target :: elemMYN(:,:)
logical, intent(inout), target :: faceYN(:,:)
type(bcType), intent(inout) :: bcdataDn(:)
type(bcType), intent(inout) :: bcdataUp(:)
real, intent(in) :: thistime
real, intent(in) :: dt
Calls
Called by
Contents
None
Call graph
rk2 calls e2r_temp, diagnostic_element_volume_conservation_fluxes, utility_advance_temp_array, overwrite_old_values, rk2_update_auxiliary_variables, diagnostic_element_volume_conservation, emr_temp
diagnostic_element_volume_conservation_fluxes calls emi_mfacedn, emi_mfaceup
rk2_update_auxiliary_variables calls element_dynamics_update, element_geometry_branch_fix, face_update, element_geometry_update, adjust_vshaped_flowrate
element_dynamics_update calls bc_applied_onelement, adjust_zero_velocity_at_zero_volume, adjust_channel_velocity_limiter, element_flowrate_update, blended_smallvolume_velocity, element_timescale
element_geometry_branch_fix calls utility_advance_temp_array, emr_temp, rectangular_junction_leg, junction_branch_sum_areas_by_direction, adjust_junction_branch_velocity_limit, junction_branch_velocity_and_flowrate_proportional_to_area
face_update calls face_hydraulic_jump, face_interp_for_upstreamchannel_to_downstreamjunction, face_interp_for_downstreamchannel_to_upstreamjunction, face_surface_elevation_interp, bc_applied_onface, face_bc_flowrate_update, face_interp_for_elem2
element_geometry_update calls utility_advance_temp_array, emr_temp, bc_applied_onelement, adjust_for_zero_geometry, rectangular_geometry_update, adjust_smallvolumes
adjust_vshaped_flowrate calls e2r_temp, utility_advance_temp_array, utility_sign_with_ones, e2yn_temp
bc_applied_onelement calls bc_onelement
adjust_for_zero_geometry calls reset_juctionbranches_for_zero_values, reset_element_for_zero_values
face_hydraulic_jump calls utility_advance_temp_array, fr_temp
adjust_zero_velocity_at_zero_volume calls zero_velocity_at_zero_volume
rectangular_geometry_update calls rectangular_junction_leg, rectangular_channel_or_junction
adjust_junction_branch_velocity_limit calls emr_velocitydn, emr_areadn, emr_flowratedn, emr_areaup, emr_flowrateup, emr_velocityup
face_interp_for_upstreamchannel_to_downstreamjunction calls utility_advance_temp_array, interp_with_junction_downstream, fyn_temp, emr_timescaleup, fr_temp
face_interp_for_downstreamchannel_to_upstreamjunction calls utility_advance_temp_array, fyn_temp, fr_temp, emr_timescaledn, interp_with_junction_upstream
element_flowrate_update calls utility_advance_temp_array, emr_temp, junction_branch_sum_areas_by_direction, adjust_junction_branch_velocity_limit, junction_branch_velocity_and_flowrate_proportional_to_area, flowrate_from_velocity
face_surface_elevation_interp calls utility_advance_temp_array, emr_lengthdn, emr_lengthup, fyn_temp, fr_temp
bc_applied_onface calls bc_onface, bc_ghost_othervalues, bc_face_othervalues
face_bc_flowrate_update calls face_bc_flowrate_update_onevalue
face_interp_for_elem2 calls utility_advance_temp_array, fyn_temp, fr_temp
blended_smallvolume_velocity calls emi_mfacedn, emi_mfaceup, emr_lengthdn, emr_velocitydn, emr_areadn, velocity_blend_with_mask, emr_lengthup, emr_flowratedn, emr_areaup, emr_flowrateup, emr_velocityup
adjust_smallvolumes calls smallvolume_identification, smallvolume_geometry
element_timescale calls bc_timescale_value, timescale_value_junction, timescale_value_channel
bc_onface calls bc_updatevalue
smallvolume_identification calls smallvolume_identification_for_element
timescale_value_junction calls utility_advance_temp_array, emr_temp, timescale_limit_junction_one_direction, timescale_junction_one_direction
interp_with_junction_downstream calls linear_interpolation
velocity_blend_with_mask calls utility_advance_temp_array, velocity_blend, smallvolume_manningsn, small_chezy_velocity
smallvolume_geometry calls smallvolume_junctionbranch_reset, smallvolume_element_geometry_reset
bc_onelement calls bc_updatevalue
timescale_value_channel calls e2r_temp, utility_advance_temp_array, e2yn_temp, timescale_limiter
interp_with_junction_upstream calls linear_interpolation
timescale_limit_junction_one_direction calls utility_advance_temp_array, timescale_limiter, emyn_temp
bc_updatevalue calls utility_linear_interpolate_within_indexlist
timescale_limiter calls apply_limiter_with_mask
time_marching calls rk2
main calls time_marching