rk2_update_auxiliary_variables – SWMMengine
rk2_update_auxiliary_variables Subroutine
21 statements
Source File
private subroutine rk2_update_auxiliary_variables(e2r_Velocity_new, eMr_Velocity_new, e2r_Volume_new, eMr_Volume_new, elem2R, elem2I, elem2YN, elemMR, elemMI, elemMYN, faceR, faceI, faceYN, bcdataDn, bcdataUp, steptime, rkiteration)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: e2r_Velocity_new
integer, intent(in) :: eMr_Velocity_new
integer, intent(in) :: e2r_Volume_new
integer, intent(in) :: eMr_Volume_new
real, intent(inout) :: elem2R(:,:)
integer, intent(inout) :: elem2I(:,:)
logical, intent(inout) :: elem2YN(:,:)
real, intent(inout), target :: elemMR(:,:)
integer, intent(inout) :: elemMI(:,:)
logical, intent(inout) :: elemMYN(:,:)
real, intent(inout) :: faceR(:,:)
integer, intent(inout) :: faceI(:,:)
logical, intent(inout) :: faceYN(:,:)
type(bcType), intent(inout) :: bcdataDn(:)
type(bcType), intent(inout) :: bcdataUp(:)
real, intent(in) :: steptime
integer, intent(in) :: rkiteration
Calls
Called by
Contents
None
Call graph
rk2_update_auxiliary_variables calls element_dynamics_update, adjust_vshaped_flowrate, element_geometry_update, face_update, element_geometry_branch_fix
element_dynamics_update calls bc_applied_onelement, adjust_zero_velocity_at_zero_volume, adjust_channel_velocity_limiter, element_flowrate_update, blended_smallvolume_velocity, element_timescale
adjust_vshaped_flowrate calls utility_sign_with_ones, e2yn_temp, e2r_temp, utility_advance_temp_array
element_geometry_update calls bc_applied_onelement, adjust_for_zero_geometry, rectangular_geometry_update, emr_temp, utility_advance_temp_array, adjust_smallvolumes
face_update calls face_hydraulic_jump, face_interp_for_downstreamchannel_to_upstreamjunction, face_interp_for_upstreamchannel_to_downstreamjunction, face_surface_elevation_interp, bc_applied_onface, face_bc_flowrate_update, face_interp_for_elem2
element_geometry_branch_fix calls rectangular_junction_leg, junction_branch_sum_areas_by_direction, adjust_junction_branch_velocity_limit, emr_temp, junction_branch_velocity_and_flowrate_proportional_to_area, utility_advance_temp_array
bc_applied_onelement calls bc_onelement
adjust_for_zero_geometry calls reset_juctionbranches_for_zero_values, reset_element_for_zero_values
face_hydraulic_jump calls utility_advance_temp_array, fr_temp
adjust_zero_velocity_at_zero_volume calls zero_velocity_at_zero_volume
rectangular_geometry_update calls rectangular_junction_leg, rectangular_channel_or_junction
adjust_junction_branch_velocity_limit calls emr_velocitydn, emr_areadn, emr_flowratedn, emr_areaup, emr_flowrateup, emr_velocityup
face_interp_for_downstreamchannel_to_upstreamjunction calls utility_advance_temp_array, fyn_temp, fr_temp, emr_timescaledn, interp_with_junction_upstream
face_interp_for_upstreamchannel_to_downstreamjunction calls utility_advance_temp_array, interp_with_junction_downstream, fyn_temp, emr_timescaleup, fr_temp
element_flowrate_update calls junction_branch_sum_areas_by_direction, adjust_junction_branch_velocity_limit, emr_temp, junction_branch_velocity_and_flowrate_proportional_to_area, utility_advance_temp_array, flowrate_from_velocity
face_surface_elevation_interp calls utility_advance_temp_array, emr_lengthdn, emr_lengthup, fyn_temp, fr_temp
bc_applied_onface calls bc_onface, bc_ghost_othervalues, bc_face_othervalues
face_bc_flowrate_update calls face_bc_flowrate_update_onevalue
face_interp_for_elem2 calls utility_advance_temp_array, fyn_temp, fr_temp
blended_smallvolume_velocity calls emi_mfaceup, emr_lengthdn, emr_velocitydn, emr_areadn, velocity_blend_with_mask, emr_lengthup, emr_flowratedn, emr_areaup, emi_mfacedn, emr_flowrateup, emr_velocityup
adjust_smallvolumes calls smallvolume_identification, smallvolume_geometry
element_timescale calls bc_timescale_value, timescale_value_junction, timescale_value_channel
bc_onface calls bc_updatevalue
smallvolume_identification calls smallvolume_identification_for_element
timescale_value_junction calls emr_temp, utility_advance_temp_array, timescale_limit_junction_one_direction, timescale_junction_one_direction
interp_with_junction_downstream calls linear_interpolation
velocity_blend_with_mask calls utility_advance_temp_array, velocity_blend, smallvolume_manningsn, small_chezy_velocity
smallvolume_geometry calls smallvolume_junctionbranch_reset, smallvolume_element_geometry_reset
bc_onelement calls bc_updatevalue
timescale_value_channel calls e2yn_temp, e2r_temp, utility_advance_temp_array, timescale_limiter
interp_with_junction_upstream calls linear_interpolation
timescale_limit_junction_one_direction calls utility_advance_temp_array, timescale_limiter, emyn_temp
bc_updatevalue calls utility_linear_interpolate_within_indexlist
timescale_limiter calls apply_limiter_with_mask
rk2 calls rk2_update_auxiliary_variables
time_marching calls rk2
main calls time_marching