subdivide_link_going_upstream – SWMMengine
subdivide_link_going_upstream Subroutine
62 statements
Source File
private subroutine subdivide_link_going_upstream(lastElem2, thisElem2, lastFace, thisFace, thisLink, elem2I, faceI, linkI, elem2R, faceR, linkR, nodeR, zDownstream)
Arguments
Type Intent Optional Attributes Name
integer, intent(inout) :: lastElem2
integer, intent(inout) :: thisElem2
integer, intent(inout) :: lastFace
integer, intent(inout) :: thisFace
integer, intent(in) :: thisLink
integer, intent(inout) :: elem2I(:,:)
integer, intent(inout) :: faceI(:,:)
integer, intent(inout) :: linkI(:,:)
real, intent(inout) :: elem2R(:,:)
real, intent(inout) :: faceR(:,:)
real, intent(in) :: linkR(:,:)
real, intent(in) :: nodeR(:,:)
real, intent(in) :: zDownstream
Calls
Called by
Contents
None
Call graph
subdivide_link_going_upstream calls setfacetype
network_data_create calls subdivide_link_going_upstream, handle_thisnode
handle_thisnode calls subdivide_link_going_upstream, handle_thisnode
network_initiation calls network_data_create
main calls network_initiation