sve_rk2_step – SWMMengine
sve_rk2_step Subroutine
106 statements
Source File
private subroutine sve_rk2_step(e2r_Volume_old, e2r_Velocity_old, eMr_Volume_old, eMr_Velocity_old, e2r_Volume_new, e2r_Velocity_new, eMr_Volume_new, eMr_Velocity_new, elem2R, elemMR, faceR, elem2I, elemMI, elem2YN, elemMYN, thiscoef)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: e2r_Volume_old
integer, intent(in) :: e2r_Velocity_old
integer, intent(in) :: eMr_Volume_old
integer, intent(in) :: eMr_Velocity_old
integer, intent(in) :: e2r_Volume_new
integer, intent(in) :: e2r_Velocity_new
integer, intent(in) :: eMr_Volume_new
integer, intent(in) :: eMr_Velocity_new
real, intent(inout), target :: elem2R(:,:)
real, intent(inout), target :: elemMR(:,:)
real, intent(in), target :: faceR(:,:)
integer, intent(in), target :: elem2I(:,:)
integer, intent(in), target :: elemMI(:,:)
logical, intent(inout) :: elem2YN(:,:)
logical, intent(inout) :: elemMYN(:,:)
real, intent(in) :: thiscoef
Calls
Contents
None
Call graph
sve_rk2_step calls e2r_temp, adjust_negative_volume_reset, emi_mfaceup, utility_advance_temp_array, emr_temp, emi_mfacedn