test_case_initiation – SWMMengine
test_case_initiation Subroutine
103 statements
Source File
public subroutine test_case_initiation(linkR, nodeR, linkI, nodeI, linkYN, nodeYN, linkName, nodeName, bcdataDn, bcdataUp)
Arguments
Type Intent Optional Attributes Name
real, intent(out), dimension(:,:), allocatable :: linkR
real, intent(out), dimension(:,:), allocatable :: nodeR
integer, intent(out), dimension(:,:), allocatable :: linkI
integer, intent(out), dimension(:,:), allocatable :: nodeI
logical, intent(out), dimension(:,:), allocatable :: linkYN
logical, intent(out), dimension(:,:), allocatable :: nodeYN
type(string), intent(out), dimension(:), allocatable :: linkName
type(string), intent(out), dimension(:), allocatable :: nodeName
type(bcType), intent(out), dimension(:), allocatable :: bcdataDn
type(bcType), intent(out), dimension(:), allocatable :: bcdataUp
Calls
Called by
Contents
None
Call graph
test_case_initiation calls control_variable_allocation, write_testcase_setup_file, this_setting_for_time_and_steps, case_y_channel_initialize
write_testcase_setup_file calls utility_check_fileopen
this_setting_for_time_and_steps calls get_dt_from_cfl, utility_round_to_significant_digits, utility_scale_of_number
case_y_channel_initialize calls bc_allocate, case_y_channel_links_and_nodes
bc_allocate calls utility_check_allocation
utility_round_to_significant_digits calls utility_scale_of_number
case_y_channel_links_and_nodes calls allocate_linknode_storage
allocate_linknode_storage calls utility_check_allocation
main calls test_case_initiation