this_setting_for_time_and_steps – SWMMengine
this_setting_for_time_and_steps Subroutine
22 statements
Source File
private subroutine this_setting_for_time_and_steps(CFL, velocity, depth, subdivide_length, first_step, last_step, display_interval, dt_significant_digits)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: CFL
real, intent(in) :: velocity(:)
real, intent(in) :: depth(:)
real, intent(in) :: subdivide_length(:)
integer, intent(in) :: first_step
integer, intent(in) :: last_step
integer, intent(in) :: display_interval
integer, intent(in) :: dt_significant_digits
Calls
Called by
Contents
None
Call graph
this_setting_for_time_and_steps calls utility_scale_of_number, utility_round_to_significant_digits, get_dt_from_cfl
utility_round_to_significant_digits calls utility_scale_of_number
test_case_initiation calls this_setting_for_time_and_steps
main calls test_case_initiation