time_marching – SWMMengine
time_marching Subroutine
55 statements
Source File
public subroutine time_marching(elem2R, elemMR, faceR, elem2I, elemMI, faceI, elem2YN, elemMYN, faceYN, bcdataDn, bcdataUp, linkI, debugfile, diagnostic, threadedfile)
Arguments
Type Intent Optional Attributes Name
real, intent(inout), target :: elem2R(:,:)
real, intent(inout), target :: elemMR(:,:)
real, intent(inout), target :: faceR(:,:)
integer, intent(inout), target :: elem2I(:,:)
integer, intent(inout), target :: elemMI(:,:)
integer, intent(inout), target :: faceI(:,:)
logical, intent(inout), target :: elem2YN(:,:)
logical, intent(inout), target :: elemMYN(:,:)
logical, intent(inout), target :: faceYN(:,:)
type(bcType), intent(inout) :: bcdataDn(:)
type(bcType), intent(inout) :: bcdataUp(:)
integer, intent(in) :: linkI(:,:)
type(debugfileType), intent(in), target :: debugfile(:)
type(diagnosticType), intent(inout), target :: diagnostic(:)
type(threadedfileType), intent(in) :: threadedfile(:)
Calls
Called by
Contents
None
Call graph
time_marching calls output_all_threaded_data_by_link, debug_output, diagnostic_froude_number, diagnostic_cfl, bc_applied_onelement, bc_applied_onface, rk2, diagnostic_volume_conservation
output_all_threaded_data_by_link calls output_one_threaded_data_by_link
diagnostic_froude_number calls diagnostic_froude_number_one
bc_applied_onelement calls bc_onelement
bc_applied_onface calls bc_face_othervalues, bc_ghost_othervalues, bc_onface
rk2 calls e2r_temp, diagnostic_element_volume_conservation_fluxes, rk2_update_auxiliary_variables, overwrite_old_values, utility_advance_temp_array, emr_temp, diagnostic_element_volume_conservation
diagnostic_volume_conservation calls total_inout_flowrate
diagnostic_element_volume_conservation_fluxes calls emi_mfaceup, emi_mfacedn
total_inout_flowrate calls inout_flowrate_from_bcdata
rk2_update_auxiliary_variables calls element_geometry_update, face_update, adjust_vshaped_flowrate, element_geometry_branch_fix, element_dynamics_update
output_one_threaded_data_by_link calls utility_check_allocation, emr_lengthup, emr_lengthdn
bc_onelement calls bc_updatevalue
bc_onface calls bc_updatevalue
element_geometry_update calls bc_applied_onelement, utility_advance_temp_array, emr_temp, adjust_for_zero_geometry, adjust_smallvolumes, rectangular_geometry_update
face_update calls bc_applied_onface, face_interp_for_downstreamchannel_to_upstreamjunction, face_interp_for_elem2, face_hydraulic_jump, face_bc_flowrate_update, face_interp_for_upstreamchannel_to_downstreamjunction, face_surface_elevation_interp
bc_updatevalue calls utility_linear_interpolate_within_indexlist
adjust_vshaped_flowrate calls e2r_temp, utility_advance_temp_array, e2yn_temp, utility_sign_with_ones
element_geometry_branch_fix calls utility_advance_temp_array, emr_temp, rectangular_junction_leg, junction_branch_velocity_and_flowrate_proportional_to_area, adjust_junction_branch_velocity_limit, junction_branch_sum_areas_by_direction
element_dynamics_update calls bc_applied_onelement, adjust_channel_velocity_limiter, blended_smallvolume_velocity, element_flowrate_update, adjust_zero_velocity_at_zero_volume, element_timescale
face_interp_for_downstreamchannel_to_upstreamjunction calls utility_advance_temp_array, emr_timescaledn, interp_with_junction_upstream, fyn_temp, fr_temp
blended_smallvolume_velocity calls emr_lengthup, emr_lengthdn, emi_mfaceup, emi_mfacedn, emr_velocitydn, emr_flowrateup, emr_flowratedn, velocity_blend_with_mask, emr_areaup, emr_velocityup, emr_areadn
face_interp_for_elem2 calls utility_advance_temp_array, fyn_temp, fr_temp
face_hydraulic_jump calls utility_advance_temp_array, fr_temp
adjust_for_zero_geometry calls reset_juctionbranches_for_zero_values, reset_element_for_zero_values
face_bc_flowrate_update calls face_bc_flowrate_update_onevalue
element_flowrate_update calls utility_advance_temp_array, emr_temp, junction_branch_velocity_and_flowrate_proportional_to_area, adjust_junction_branch_velocity_limit, junction_branch_sum_areas_by_direction, flowrate_from_velocity
face_interp_for_upstreamchannel_to_downstreamjunction calls utility_advance_temp_array, emr_timescaleup, fyn_temp, fr_temp, interp_with_junction_downstream
adjust_junction_branch_velocity_limit calls emr_velocitydn, emr_flowrateup, emr_flowratedn, emr_areaup, emr_velocityup, emr_areadn
adjust_zero_velocity_at_zero_volume calls zero_velocity_at_zero_volume
element_timescale calls timescale_value_junction, bc_timescale_value, timescale_value_channel
adjust_smallvolumes calls smallvolume_geometry, smallvolume_identification
face_surface_elevation_interp calls utility_advance_temp_array, emr_lengthup, emr_lengthdn, fyn_temp, fr_temp
rectangular_geometry_update calls rectangular_junction_leg, rectangular_channel_or_junction
timescale_value_junction calls utility_advance_temp_array, emr_temp, timescale_limit_junction_one_direction, timescale_junction_one_direction
interp_with_junction_upstream calls linear_interpolation
timescale_value_channel calls e2r_temp, utility_advance_temp_array, e2yn_temp, timescale_limiter
velocity_blend_with_mask calls utility_advance_temp_array, smallvolume_manningsn, velocity_blend, small_chezy_velocity
interp_with_junction_downstream calls linear_interpolation
smallvolume_geometry calls smallvolume_junctionbranch_reset, smallvolume_element_geometry_reset
smallvolume_identification calls smallvolume_identification_for_element
timescale_limiter calls apply_limiter_with_mask
timescale_limit_junction_one_direction calls utility_advance_temp_array, timescale_limiter, emyn_temp
main calls time_marching