utility_check_allocation – SWMMengine
utility_check_allocation Subroutine
11 statements
Source File
public subroutine utility_check_allocation(allocation_status, emsg)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: allocation_status
character(len=*), intent(in) :: emsg
Called by
Contents
None
Call graph
output_threaded_by_link_initialize calls utility_check_allocation
debug_initialize calls utility_check_allocation
allocate_data_storage calls utility_check_allocation
allocate_linknode_storage calls utility_check_allocation
diagnostic_initialize calls utility_check_allocation
output_one_threaded_data_by_link calls utility_check_allocation
bc_allocate calls utility_check_allocation
output_all_threaded_data_by_link calls output_one_threaded_data_by_link
case_y_channel_initialize calls bc_allocate, case_y_channel_links_and_nodes
network_initiation calls allocate_data_storage
case_simple_channel_initialize calls bc_allocate, case_simple_channel_links_and_nodes
case_simple_channel_links_and_nodes calls allocate_linknode_storage
main calls output_threaded_by_link_initialize, debug_initialize, diagnostic_initialize, network_initiation, test_case_initiation, time_marching
case_y_channel_links_and_nodes calls allocate_linknode_storage
test_case_initiation calls case_y_channel_initialize
time_marching calls output_all_threaded_data_by_link