utility_advance_temp_array – SWMMengine
utility_advance_temp_array Function
9 statements
Source File
public function utility_advance_temp_array(next_temparray, temparraysize)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: next_temparray
integer, intent(in) :: temparraysize
Return Value integer
Called by
Contents
None
Call graph
timescale_value_junction calls utility_advance_temp_array, timescale_limit_junction_one_direction
junction_branch_average_for_directions_then_sum calls utility_advance_temp_array
timescale_limit_junction_one_direction calls utility_advance_temp_array
adjust_vshaped_flowrate calls utility_advance_temp_array
explicit_test_advance calls utility_advance_temp_array, adjust_vshaped_flowrate, test_face_update
rk2 calls utility_advance_temp_array, rk2_update_auxiliary_variables
element_flowrate_update calls utility_advance_temp_array
timescale_value_channel calls utility_advance_temp_array
face_interp_for_upstreamchannel_to_downstreamjunction calls utility_advance_temp_array
velocity_blend_with_mask calls utility_advance_temp_array
face_surface_elevation_interp calls utility_advance_temp_array
junction_branch_summation_and_updown_average calls utility_advance_temp_array
test_face_update calls utility_advance_temp_array
junction_adjacent_element_average calls utility_advance_temp_array
junction_branch_average_of_inflows_and_outflows calls utility_advance_temp_array
element_geometry_update calls utility_advance_temp_array
face_interp_for_downstreamchannel_to_upstreamjunction calls utility_advance_temp_array
sve_rk2_step calls utility_advance_temp_array
explicit_euler_advance calls utility_advance_temp_array, adjust_vshaped_flowrate
face_interp_for_elem2 calls utility_advance_temp_array
face_hydraulic_jump calls utility_advance_temp_array
element_geometry_branch_fix calls utility_advance_temp_array
face_update calls face_interp_for_upstreamchannel_to_downstreamjunction, face_surface_elevation_interp, face_interp_for_downstreamchannel_to_upstreamjunction, face_interp_for_elem2, face_hydraulic_jump
blended_smallvolume_velocity calls velocity_blend_with_mask
initial_junction_conditions calls junction_adjacent_element_average, junction_branch_average_of_inflows_and_outflows
initial_condition_setup calls element_geometry_update, face_update, initial_junction_conditions, element_dynamics_update
time_marching calls rk2
element_dynamics_update calls element_flowrate_update, blended_smallvolume_velocity, element_timescale
element_timescale calls timescale_value_junction, timescale_value_channel
junction_geometry_setup calls junction_branch_average_for_directions_then_sum, junction_branch_summation_and_updown_average
rk2_update_auxiliary_variables calls adjust_vshaped_flowrate, element_geometry_update, element_geometry_branch_fix, face_update, element_dynamics_update
network_initiation calls junction_geometry_setup
main calls initial_condition_setup, time_marching, network_initiation