utility_sign_with_ones – SWMMengine
utility_sign_with_ones Function
5 statements
Source File
public pure elemental function utility_sign_with_ones(inarray) result(outarray)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: inarray
Return Value real
Called by
Contents
None
Call graph
adjust_vshaped_flowrate calls utility_sign_with_ones
explicit_test_advance calls adjust_vshaped_flowrate
rk2_update_auxiliary_variables calls adjust_vshaped_flowrate
explicit_euler_advance calls adjust_vshaped_flowrate
rk2 calls rk2_update_auxiliary_variables
time_marching calls rk2
main calls time_marching