velocity_blend_with_mask – SWMMengine
velocity_blend_with_mask Subroutine
50 statements
Source File
private subroutine velocity_blend_with_mask(elemR, elemI, elemYN, faceR, next_er_temparray, er_n_temp, er_Temp, er_Velocity_new, er_Flowrate, er_Length, er_Area, er_HydRadius, er_SmallVolumeRatio, eYN_IsSmallVolume, ei_roughness_type, er_Roughness, ei_elem_type, elemType, ei_Mface_u, ei_Mface_d)
Arguments
Type Intent Optional Attributes Name
real, intent(inout), target :: elemR(:,:)
integer, intent(in), target :: elemI(:,:)
logical, intent(in) :: elemYN(:,:)
real, intent(in) :: faceR(:,:)
integer, intent(inout) :: next_er_temparray
integer, intent(in) :: er_n_temp
integer, intent(in) :: er_Temp(:)
integer, intent(in) :: er_Velocity_new
integer, intent(in) :: er_Flowrate
integer, intent(in) :: er_Length
integer, intent(in) :: er_Area
integer, intent(in) :: er_HydRadius
integer, intent(in) :: er_SmallVolumeRatio
integer, intent(in) :: eYN_IsSmallVolume
integer, intent(in) :: ei_roughness_type
integer, intent(in) :: er_Roughness
integer, intent(in) :: ei_elem_type
integer, intent(in) :: elemType
integer, intent(in) :: ei_Mface_u
integer, intent(in) :: ei_Mface_d
Calls
Called by
Contents
None
Call graph
velocity_blend_with_mask calls smallvolume_manningsn, utility_advance_temp_array, small_chezy_velocity, velocity_blend
blended_smallvolume_velocity calls velocity_blend_with_mask
element_dynamics_update calls blended_smallvolume_velocity
rk2_update_auxiliary_variables calls element_dynamics_update
initial_condition_setup calls element_dynamics_update
main calls initial_condition_setup, time_marching
rk2 calls rk2_update_auxiliary_variables
time_marching calls rk2