write_testcase_setup_file – SWMMengine
write_testcase_setup_file Subroutine
58 statements
Source File
private subroutine write_testcase_setup_file(Froude, CFL, flowrate, velocity, depth_upstream, depth_dnstream, breadth, area, total_length, subdivide_length, lowerZ, upperZ, ManningsN)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: Froude(:)
real, intent(in) :: CFL
real, intent(in) :: flowrate(:)
real, intent(in) :: velocity(:)
real, intent(in) :: depth_upstream(:)
real, intent(in) :: depth_dnstream(:)
real, intent(in) :: breadth(:)
real, intent(in) :: area(:)
real, intent(in) :: total_length(:)
real, intent(in) :: subdivide_length(:)
real, intent(in) :: lowerZ(:)
real, intent(in) :: upperZ(:)
real, intent(in) :: ManningsN(:)
Calls
Called by
Contents
None
Call graph
write_testcase_setup_file calls utility_check_fileopen
test_case_initiation calls write_testcase_setup_file
main calls test_case_initiation